version: "3.3"
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  tomcat:
    build:
      tomcat
    image: "welchie99/tomcat:${TOMCAT_VERSION}"
    ports:
      - "8888:8080"
    volumes:
      - tomcat:/var/lib/tomcat/data
    healthcheck:
      test: netstat -lan | grep 8888 | wc -l
      interval: 1m30s
      timeout: 10s
      retries: 3
volumes:
  postgres:
  tomcat:
